contents:
  repositories:
  - https://dl-cdn.alpinelinux.org/alpine/v3.16/main
  packages:
  - busybox
  - alpine-baselayout

accounts:
  groups:
  - groupname: nonroot
    gid: 10000
  users:
  - username: nonroot
    uid: 10000
  run-as: nonroot

environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

os-release:
  version-id: '3.16'

archs:
 - x86_64
#  - arm64
