name: Deploy Images
on:
  push:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/dansiviter

jobs:
  apko:
    runs-on: ubuntu-latest
    container:
      image: cgr.dev/chainguard/apko:v0.25.1
    permissions:
      packages: write
      security-events: write
    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Registry Login
      uses: docker://cgr.dev/chainguard/apko:v0.25.1
      with:
        args: login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

    - name: Build MiniRootFS
      uses: docker://cgr.dev/chainguard/apko:v0.25.1
      with:
        args: >
          publish ./apko/minirootfs.yml
          ${{ env.REGISTRY }}/alpine:3.21-minirootfs
          ${{ env.REGISTRY }}/alpine:3-minirootfs
          ${{ env.REGISTRY }}/alpine:minirootfs

    - name: Scan for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@0.3.0
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ env.REGISTRY }}/alpine:3.16-minirootfs
        args: --file=./apko/minirootfs.yml

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif

    - name: Build base
      uses: docker://cgr.dev/chainguard/apko:v0.25.1
      with:
        args: >
          publish ./apko/base.yml
          ${{ env.REGISTRY }}/alpine:3.21-base
          ${{ env.REGISTRY }}/alpine:3-base
          ${{ env.REGISTRY }}/alpine:base

    - name: Build musl
      uses: docker://cgr.dev/chainguard/apko:v0.25.1
      with:
        args: >
          publish ./apko/musl.yml
          ${{ env.REGISTRY }}/alpine:3.21-musl
          ${{ env.REGISTRY }}/alpine:3-musl
          ${{ env.REGISTRY }}/alpine:musl

    - name: Build JLink
      uses: docker://cgr.dev/chainguard/apko:v0.25.1
      with:
        args: >
          publish ./apko/jlink.yml
          ${{ env.REGISTRY }}/alpine:3.21-jlink
          ${{ env.REGISTRY }}/alpine:3-jlink
          ${{ env.REGISTRY }}/alpine:jlink

    - name: Build JRE17
      uses: docker://cgr.dev/chainguard/apko:v0.25.1
      with:
        args: >
          publish ./apko/jre17.yml
          ${{ env.REGISTRY }}/alpine:3.21-jre17
          ${{ env.REGISTRY }}/alpine:3-jre17
          ${{ env.REGISTRY }}/alpine:jre17

    - name: Build JRE21
      uses: docker://cgr.dev/chainguard/apko:v0.25.1
      with:
        args: >
          publish ./apko/jre21.yml
          ${{ env.REGISTRY }}/alpine:3.21-jre17
          ${{ env.REGISTRY }}/alpine:3-jre17
          ${{ env.REGISTRY }}/alpine:jre17
