name: Deploy Images
on:
  push:

env:
  REGISTRY: ghcr.io/dansiviter

jobs:
  apko:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chainguard-dev/apko:v0.3.3
    permissions:
      packages: write
      security-events: write
    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Registry Login
      uses: docker://ghcr.io/chainguard-dev/apko:v0.3.3
      with:
        args: login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

    - name: Build base
      uses: docker://ghcr.io/chainguard-dev/apko:v0.3.3
      with:
        args: >
          publish ./apko/base.yml
          ${{ env.REGISTRY }}/alpine:3.15-distroless
          ${{ env.REGISTRY }}/alpine:3-distroless
          ${{ env.REGISTRY }}/alpine:distroless

    - name: Scan for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@0.3.0
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: ${{ env.REGISTRY }}/alpine:3.15-distroless

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif

    - name: Build JLink
      uses: docker://ghcr.io/chainguard-dev/apko:v0.3.3
      with:
        args: >
          publish ./apko/jlink.yml
          ${{ env.REGISTRY }}/alpine:3.15-jlink-distroless
          ${{ env.REGISTRY }}/alpine:3-jlink-distroless
          ${{ env.REGISTRY }}/alpine:jlink-distroless

    - name: Build JRE17
      uses: docker://ghcr.io/chainguard-dev/apko:v0.3.3
      with:
        args: >
          publish ./apko/jre17.yml
          ${{ env.REGISTRY }}/alpine:3.15-jre17-distroless
          ${{ env.REGISTRY }}/alpine:3-jre17-distroless
          ${{ env.REGISTRY }}/alpine:jre17-distroless
