name: Deploy Images
on:
  push:

env:
  REGISTRY: ghcr.io/dansiviter

jobs:
  apko:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chainguard-dev/apko:v0.3.3
    permissions:
      packages: write
    steps:
    - name: Checkout project
      uses: actions/checkout@v3

    - name: Registry Login
      uses: docker://ghcr.io/chainguard-dev/apko:v0.3.3
      with:
        args: login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

    - name: Build base
      uses: docker://ghcr.io/chainguard-dev/apko:v0.3.3
      with:
        args: >
          publish ./apko/base.yml
          ${{ env.REGISTRY }}/alpine:3.15-distroless
          ${{ env.REGISTRY }}/alpine:3-distroless
          ${{ env.REGISTRY }}/alpine:distroless

    - name: Build JLink
      uses: docker://ghcr.io/chainguard-dev/apko:v0.3.3
      with:
        args: >
          publish ./apko/jlink.yml
          ${{ env.REGISTRY }}/alpine:3.15-jlink-distroless
          ${{ env.REGISTRY }}/alpine:3-jlink-distroless
          ${{ env.REGISTRY }}/alpine:jlink-distroless

    - name: Build JRE17
      uses: docker://ghcr.io/chainguard-dev/apko:v0.3.3
      with:
        args: >
          publish ./apko/jre17.yml
          ${{ env.REGISTRY }}/alpine:3.15-jre17-distroless
          ${{ env.REGISTRY }}/alpine:3-jre17-distroless
          ${{ env.REGISTRY }}/alpine:jre17-distroless
